# docker-compose.default.yml
version: '2.2'

networks:
  app-network:
    name: docker-network
    driver: bridge

services:
  hotrotaichinh_db:
    container_name: hotrotaichinh_db
    command:
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv=""
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootducdv@79
      - MYSQL_DATABASE=hotrotaichinh
      - MYSQL_USER=ducdv79
      - MYSQL_PASSWORD=ducdv@79
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    ports:
      - 3306:3306
    volumes:
      - ./api/mysql/my.cnf:/etc/mysql/my.cnf
      - hotrotaichinh_db:/var/lib/mysql
    networks:
      - app-network

  hotrotaichinh_api:
    container_name: hotrotaichinh_api
    build:
      context: ./api
      dockerfile: api.dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./api:/app
      - ./api/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - hotrotaichinh_db
    environment:
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_HOST=hotrotaichinh_db
      - DB_DATABASE=hotrotaichinh
      - DB_USERNAME=ducdv79
      - DB_PASSWORD=ducdv@79
    networks:
      - app-network

  hotrotaichinh_app:
    container_name: hotrotaichinh_app
    build:
      context: ./app
      dockerfile: app.dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/app/
      - hotrotaichinh_app:/app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: npm start

volumes:
  hotrotaichinh_db:
    driver: local

  hotrotaichinh_app:
    driver: local
