# docker-compose.default.yml
version: '2.2'

networks:
  app-network:
    name: hotrotaichinh
    driver: bridge

services:
  hotrotaichinh_app:
    container_name: hotrotaichinh_app
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    networks:
      - app-network