# docker-compose.default.yml
version: '2.2'

networks:
  app-network:
    name: hotrotaichinh
    driver: bridge

services:
  hotrotaichinh_app:
    container_name: hotrotaichinh_app
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - hotrotaichinh_app:/app
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: npm start

volumes:
  hotrotaichinh_app:
    driver: local
