# docker-compose.yml
version: '2.2'

networks:
  app-network:
    name: hotrotaichinh
    driver: bridge

services:
  hotrotaichinh_db:
    container_name: hotrotaichinh_db
    command:
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv=""
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootducdv@79
      - MYSQL_DATABASE=hotrotaichinh
      - MYSQL_USER=ducdv79
      - MYSQL_PASSWORD=ducdv@79
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - hotrotaichinh_db:/var/lib/mysql
    networks:
      - app-network

  hotrotaichinh_api:
    container_name: hotrotaichinh_api
    build:
      context: ./
      dockerfile: api.dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - hotrotaichinh_db
    environment:
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_HOST=hotrotaichinh_db
      - DB_DATABASE=hotrotaichinh
      - DB_USERNAME=root
      - DB_PASSWORD=ducdv@79
    networks:
      - app-network

volumes:
  hotrotaichinh_db:
    driver: local
